steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud functions deploy HelloWorldGitFunction \
            --region=global \
            --runtime=java17 \
            --trigger-http \
            --entry-point=com.wannacall.lambda.HelloWorld \
            --allow-unauthenticated \
            --set-env-vars= \
            --timeout=30 \
            --memory=256 \
            --source=src/main/java \
            --project=wannacall-server
options:
  logging: CLOUD_LOGGING_ONLY